return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "black",
      "stylua",
      "blade-formatter",
      "shellcheck",
      "shfmt",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "dot-language-server",
      "flake8",
      "hadolint",
      "eslint_d",
      "intelephense",
      "tailwindcss-language-server",
      "rustywind",
      "phpstan",
      "pint",
      "pyright",
      "prettierd",
    },
  },
}
